### ISSUE TITLE
android端加密，java服务端无法解密

### ISSUE THREAD

**Issue by androiddan** [wxmylife/RSA_AES#1]
Android端使用公钥加密，服务端私钥解密，加密后256个字节，服务端解密之后还是256个字节，按照道理来说应该是原文的长度20字节。我在安卓自己环境加解密都没问题，java端也是，但是android -> 服务端就有无法解密的问题。

**Comment by wxmylife** [comment]
你是单独用的RSA，还是AES和RSA混合使用？

**Comment by androiddan** [comment]
现在测试的是单独使用RSA

**Comment by androiddan** [comment]
安卓和java后台分别使用的android和web下的加密工具
我的测试流程是这样：android公钥加密一个字符串的byte[]，然后byte2hex()，拿到日志，到java项目中hex2byte()，使用私钥解密。没有报错，但是解出来的不是原文。

**Comment by wxmylife** [comment]
私钥进行PKCS#8编码了吗？

**Comment by wxmylife** [comment]
> 机器人端使用公钥加密，服务端私钥解密，加密后256个字节，服务端解密之后还是256个字节，按照道理来说应该是原文的长度20字节。我在安卓自己环境加解密都没问题，java端也是，但是android - >服务端就有无法解密的问题。

如果直接使用私钥解密，是解密会解密出错的，通过对私钥进行PKCS#8编码才可以解密

**Comment by androiddan** [comment]
解决了，我这边两套密钥，结果就弄混了。。。
